nome = str(input('Qual seu nome completo? '))
print('\n')
print('-'*50)
print('\n')
print('Seu nome em maiúsculo é', nome.upper())
print('Seu nome em minúsculo fica', nome.lower())
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letas'.format(separa[0], len(separa[0])))
print('\n')
print('-'*50)